#!/bin/bash

if [[ "$1" == "clean" ]]; then
    rm -f cscope.in.out  cscope.out  cscope.po.out  tags;
    exit 0;
fi

find . -name "*\.java" -o -name "*\.c" -o -name "*\.cpp" -o -name "*\.h" -o -name "*\.cc" -o -name "*\.py" -o -name "*.\python" > cscope.files
cscope -bkq -i cscope.files
ctags -R
rm -f cscope.files

